// src/lib/theorems.ts
import { Theorem } from './types';

// The 'id' is intentionally omitted here. It will be auto-generated by Firestore.
// The 'owner' field will be set to the current admin user when seeding.
// This is the list used for the initial database seed.
export const seedTheorems: Omit<Theorem, 'id' | 'owner'>[] = [
  {
    name: "Cantor's Diagonal Argument",
    adminApproved: true,
    order: 0,
  },
  {
    name: 'Gödel\'s Incompleteness Theorems',
    adminApproved: true,
    order: 1,
  },
  {
    name: 'The Halting Problem',
    adminApproved: true,
    order: 2,
  },
];

// This is the master list for the combobox on the admin page.
export const wellKnownTheorems = [
    // Foundational Math
    'Pythagorean Theorem',
    'Fundamental Theorem of Arithmetic',
    'Fundamental Theorem of Algebra',
    'Fundamental Theorem of Calculus',
    'Euclid\'s Theorem on Infinite Primes',

    // Analysis
    'Intermediate Value Theorem',
    'Mean Value Theorem',
    'Extreme Value Theorem',
    'Bolzano-Weierstrass Theorem',
    'Heine-Borel Theorem',
    'Taylor\'s Theorem',

    // Algebra
    'Binomial Theorem',
    'Cayley-Hamilton Theorem',
    'Lagrange\'s Theorem (Group Theory)',
    'Sylow Theorems',
    'Isomorphism Theorems',
    'Galois Theory Main Theorem',
    
    // Linear Algebra
    'Rank-Nullity Theorem',
    'Spectral Theorem',
    'Cayley-Hamilton Theorem',
    
    // Number Theory
    'Chinese Remainder Theorem',
    'Fermat\'s Little Theorem',
    'Euler\'s Totient Theorem',
    'Quadratic Reciprocity',
    'Prime Number Theorem',
    
    // Logic and Set Theory
    "Cantor's Diagonal Argument",
    "Cantor's Theorem",
    "Gödel's Incompleteness Theorems",
    'Diagonal Lemma',
    'Tarski\'s Undefinability Theorem',
    'Löb\'s Theorem',
    'Compactness Theorem',
    'Completeness Theorem',

    // Topology
    'Brouwer Fixed Point Theorem',
    'Hairy Ball Theorem',
    'Jordan Curve Theorem',
    'Tietze Extension Theorem',
    
    // Computer Science
    'The Halting Problem',
    'Cook-Levin Theorem (NP-Completeness of SAT)',
    'Master Theorem for Recurrence Relations',
    'CAP Theorem (Brewer\'s Theorem)',
    'Turing\'s Thesis',
    'Church-Turing Thesis',
    'Rice\'s Theorem',
    'No-Cloning Theorem',

    // Quantum Computing
    'Bell\'s Theorem',
    'Shor\'s Algorithm',
    'Grover\'s Algorithm',
    'Quantum Threshold Theorem',
    'Solovay-Kitaev Theorem',
] as const;
