// This file is now used to seed the database with the initial set of theorems.
import { Theorem } from './types';

// The 'id' is intentionally omitted here. It will be auto-generated by Firestore.
// The 'owner' field will be set to the current admin user when seeding.
export const seedTheorems: Omit<Theorem, 'id' | 'owner'>[] = [
  {
    name: "Cantor's Diagonal Argument",
    statement: "Cantor's diagonal argument is a proof that there are infinite sets which cannot be put into one-to-one correspondence with the infinite set of natural numbers. Such sets are known as uncountable sets. The proof shows that the set of all real numbers is uncountable.",
    adminApproved: true,
    order: 0,
  },
  {
    name: 'Gödel\'s Incompleteness Theorems',
    statement: 'The first incompleteness theorem states that in any consistent formal system F within which a certain amount of elementary arithmetic can be carried out, there are statements of the language of F which can neither be proved nor disproved in F. The second incompleteness theorem, an extension of the first, shows that the system cannot prove its own consistency.',
    adminApproved: true,
    order: 1,
  },
  {
    name: 'The Halting Problem',
    statement: 'The halting problem is the problem of determining, from a description of an arbitrary computer program and an input, whether the program will finish running or continue to run forever. Alan Turing proved in 1936 that a general algorithm to solve the halting problem for all possible program-input pairs cannot exist.',
    adminApproved: true,
    order: 2,
  },
  {
    name: 'Diagonal Lemma',
    statement: 'The diagonal lemma states that for any formula F(x) in a formal system that can represent all computable functions, there is a sentence S such that S is provably equivalent to F(⌈S⌉), where ⌈S⌉ is the Gödel number of S. This is a key result used in proving Gödel\'s incompleteness theorems.',
    adminApproved: true,
    order: 3,
  },
  {
    name: 'Fundamental Theorem of Calculus',
    statement: 'The fundamental theorem of calculus relates the concept of differentiating a function with the concept of integrating a function. The first part states that the definite integration of a function is related to its antiderivative, and can be reversed by differentiation. The second part states that the definite integral of a function can be computed by using any one of its infinitely many antiderivatives.',
    adminApproved: true,
    order: 4,
  },
  {
    name: 'Fundamental Theorem of Arithmetic',
    statement: 'The fundamental theorem of arithmetic states that every integer greater than 1 either is a prime number itself or can be represented as the product of prime numbers and that, moreover, this representation is unique, up to the order of the factors.',
    adminApproved: true,
    order: 5,
  },
  {
    name: 'Mean Value Theorem',
    statement: 'The mean value theorem states that for a given planar arc between two endpoints, there is at least one point at which the tangent to the arc is parallel to the secant through its endpoints.',
    adminApproved: true,
    order: 6,
  },
  {
    name: 'Intermediate Value Theorem',
    statement: 'In mathematical analysis, the intermediate value theorem states that if a continuous function, f, with an interval, [a, b], as its domain, takes values f(a) and f(b) at each end of the interval, then it also takes any value between f(a) and f(b) at some point within the interval.',
    adminApproved: true,
    order: 7,
  },
  {
    name: 'Rank-Nullity Theorem',
    statement: 'In mathematics, the rank-nullity theorem is a theorem in linear algebra, which asserts that the dimension of the domain of a linear map is the sum of its rank and its nullity.',
    adminApproved: true,
    order: 8,
  },
];
