// This file is now used to seed the database with the initial set of theorems.
import { Theorem } from './types';

// The 'id' is intentionally omitted here. It will be auto-generated by Firestore.
// The 'owner' field will be set to the current admin user when seeding.
export const seedTheorems: Omit<Theorem, 'id' | 'owner'>[] = [
  {
    name: "Cantor's Diagonal Argument",
    adminApproved: true,
    order: 0,
  },
  {
    name: 'Gödel\'s Incompleteness Theorems',
    adminApproved: true,
    order: 1,
  },
  {
    name: 'The Halting Problem',
    adminApproved: true,
    order: 2,
  },
  {
    name: 'Diagonal Lemma',
    adminApproved: true,
    order: 3,
  },
  {
    name: 'Fundamental Theorem of Calculus',
    adminApproved: true,
    order: 4,
  },
  {
    name: 'Fundamental Theorem of Arithmetic',
    adminApproved: true,
    order: 5,
  },
  {
    name: 'Mean Value Theorem',
    adminApproved: true,
    order: 6,
  },
  {
    name: 'Intermediate Value Theorem',
    adminApproved: true,
    order: 7,
  },
  {
    name: 'Rank-Nullity Theorem',
    adminApproved: true,
    order: 8,
  },
];
